# Site settings
title: Tomche Delev
email: tomce.delev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal web site
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tdelev.github.io" # the base hostname & protocol for your site
twitter_username: tdelev
github_username:  tdelev
collections:
  article:
    output: true    
defaults:
  - scope:
      path: ""
      type: article
    values:
      layout: articles
      icon: beer
permalink: pretty
# Build settings
markdown: kramdown

kramdown:
  auto_ids: true
  input: GFM
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false
  hard_wrap: false
